### ISSUE TITLE
languages.yml certificate has expired

### ISSUE THREAD

**Issue by SamStenner** [Nixinova/LinguistJS#20]
It seems that `https://raw.githubusercontent.com/github/linguist/HEAD/lib/linguist/languages.yml` is now a dead link as the certificate has expired. Not sure if this is an issue with Github. Instead use `https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml`

This has brought down our production app.

**Comment by Nixinova** [comment]
Is this still a problem? I dont think swapping `HEAD` for `master` would be a fix for the problem; if the certificate on GitHub's end is expired there's nothing that can be done on Linguist's end.

If web request failure breaks your app I'd recommend using the `offline` option to avoid fetching the data from GitHub on each run, and instead uses cached data files.

**Comment by Nixinova** [comment]
Closing as not an issue. /HEAD/ should always work and if it doesn't thats a problem on GitHub's end; use the `offline` flag to ensure web connectivity is not mandatory.
