### ISSUE TITLE
CLI --ignored-files behavior differs from readme

### ISSUE THREAD

**Issue by AssBackwards** [Nixinova/LinguistJS#22]
Greetings!

I've only used this package from the CLI and I have discovered that --ignoredFiles only seems to take one blob. However, I can specify --ignoredFiles multiple times to specify multiple blobs.

I'm using PowerShell and have not tried bash.

I found that this does not work:
```ps1
linguist-js.ps1 --offline --json --analyze . --quick --ignoredFiles "*.txt *.xml"
```

but this does work:
```ps1
linguist-js.ps1 --offline --json --analyze . --quick --ignoredFiles "*.txt --ignoredFiles *.xml"
```

I'd like to update the readme to reflect this.

**Comment by Nixinova** [comment]
You're not meant to pass it as a single string, it's meant to be a plain list: 

- :x: `linguist -a . --ignoredFiles "*.txt *.json"`
- ✅ `linguist -a . --ignoredFiles *.txt *.json`

But yes what you have suggested does also work. I'll update the readme to include both ways.
