### ISSUE TITLE
Passing a string as raw input does not work - the string is interpreted as a file name

### ISSUE THREAD

**Issue by princefishthrower** [Nixinova/LinguistJS#30]
As the title states, passing a string as the raw input to interperet / analyse doesn't work. For just a simple snippet of JavaScript code:

```ts
import linguest from "linguist-js";

const results = await linguist('console.log("Hello, world!");');
```

throws and exception:

```
null false Error: ENOENT: no such file or directory, scandir '/Users/chris/enterprise/codevideo/syntax-spy/console.log("Hello, world!");'
    at Object.readdirSync (node:fs:1514:26)
    at walk (/Users/chris/enterprise/codevideo/syntax-spy/node_modules/linguist-js/dist/helpers/walk-tree.js:25:36)
    at analyse (/Users/chris/enterprise/codevideo/syntax-spy/node_modules/linguist-js/dist/index.js:86:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/myrepository/path/root/console.log("Hello, world!");'
}
```

I took a look at the types:

```ts
async function analyse(path?: string, opts?: T.Options): Promise<T.Results>
async function analyse(paths?: string[], opts?: T.Options): Promise<T.Results>
async function analyse(rawInput?: string | string[], opts: T.Options = {}): Promise<T.Results> {
	const useRawContent = opts.fileContent !== undefined;
	const input = [rawInput ?? []].flat();
	const manualFileContent = [opts.fileContent ?? []].flat();

// ....

```

So then I assumed passing an empty object as the options i.e., `{}`, would definitely tell `linguist-js` that I want the input to be interpreted as `rawInput`, i.e.:

```ts
const results = await linguist(code, {});
```

but unfortunately this also results in the same error. 

Have I interpreted the types wrong? Do I need to pass some special flag to signal that the string I am passing is raw input and not a file name?

**Comment by Nixinova** [comment]
Hi, when parsing raw file content you need to use the `fileContent` key in the options.
The first input is for putting the list of filenames only.

This is how you use the raw input feature:
```js
const fileNames = ['file1.ts', 'file2.ts', 'ignoreme'];
const fileContent = ['#!/usr/bin/env node', 'console.log("Example");', '"ignored"'];
const options = { ignoredFiles: 'ignore*' };
const { files, languages, unknown } = await linguist(fileNames, { fileContent, ...options });
```
I'll update the documentation of the readme to make this more clear.

**Comment by Nixinova** [comment]
This is out of scope of this program then unfortunately. Not even GitHub.com with all its might does analysis like that for files. This program requires at least one hint of classification, like a file name, hashbang, modeline, etc, otherwise it hasn't a clue.

**Comment by Nixinova** [comment]
@princefishthrower Something like this seems more what you're after: https://github.com/microsoft/vscode-languagedetection
