### ISSUE TITLE
2.7.0 missing from npmjs.org

### ISSUE THREAD

**Issue by drodil** [Nixinova/LinguistJS#33]
Version 2.7.0 seems to be released at least according to changelog but it is missing from the registry. Could this be released there too, thanks!

**Comment by Nixinova** [comment]
It's available under the `pre` tag due to being less performant than v2.6. Install with `npm install linguist-js@pre`.
When I fix the performance downgrade I will push it to `@latest`.

**Comment by drodil** [comment]
Oh, okay, thanks for the info. Unfortunately we cannot use the @pre scoped versions as our internal registry blocks all those releases 😢 Have to wait for the proper release! Thanks again!
